name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_test_push:
    name: build_test_push
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: mmeeww # name of Docker Hub ID
      IMAGE_NAME: learning-golang-orchestrion

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0

      - name: Build Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}
          registry: docker.io
          tag: latest
          buildArgs: "DD_GIT_REPOSITORY_URL=github.com/jon94/learn-golang,DD_GIT_COMMIT_SHA=$(git rev-parse HEAD)"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
